[package]
name = "driver"
version = "0.1.0"
authors = ["sKyrBBit <iamskyrabbit@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
rcwt = { path = "../rcwt" }
rlisp = { path = "../rlisp" }
clap = "2.20"