[package]
name = "driver"
version = "0.1.0"
authors = ["skyrabbit <iamskyrabbit@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.110", features = ["derive"] }
serde_yaml = "0.8.12"
clap = "2.33.1"
rcwt = { path = "../rcwt" }
rlisp = { path = "../rlisp" }